spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/h2_db/querydsl
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create    # 애플리케이션 실행 시점에 테이블을 drop 하고, 다시 생성
    show-sql: true        # sql 문 system.out 에 indent 맞춰서 출력
    properties:
      hibernate:
        format_sql: true    # logger 이용
        use_sql_comments: true    # 실행되는 JPQL 이 실행되는 쿼리 상단에 주석 형태로 print 된다.

#logging.level:
#  org.hibernate.SQL: debug
#  org.hibernate.type: trace     # 실행된 쿼리에서 binding parameter 를 보여줌 -> 별도의 라인에서 보여주기 때문에 좀 불편함
